spring:
  datasource:
    url: jdbc:postgresql://tiny.db.elephantsql.com:5432/smwvnnzb
    username: smwvnnzb
    password: ASe7NRC7LyqcWkWT6Z5R_xLaPt1LdxYp
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  kafka:
    bootstrap-servers:
      - dory-01.srvs.cloudkafka.com:9094
      - dory-02.srvs.cloudkafka.com:9094
      - dory-03.srvs.cloudkafka.com:9094
    consumer:
      group-id: 9v9yq2pk-consumers
    properties:
      sasl:
        jaas:
          config: org.apache.kafka.common.security.scram.ScramLoginModule required username="9v9yq2pk" password="9BrxJVByunM2fJ_qZbP3IhC_xo-Qu66F";
cloudkarafka:
  topic:
    model: 9v9yq2pk-model
    nick: 9v9yq2pk-nick
    publisher: 9v9yq2pk-publisher
    album: 9v9yq2pk-album
