spring:
  datasource:
    url: jdbc:postgresql://jelani.db.elephantsql.com:5432/gozuzqsr
    username: gozuzqsr
    password: aRKw9m4PrpNfnua0QuUH5CNulXBMl6ya
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
